### ISSUE TITLE
when will you release your code?

### ISSUE THREAD

**Issue by Mrkkew** [ziplab/FASeg#1]
Interesting job ! When will you release your source code?

**Comment by Charleshhy** [comment]
Hi Mrkkew,

Thanks for your interest! I am planning to release the code in early or late next month :)

Kind regards,
Haoyu

**Comment by Charleshhy** [comment]
Hi Mrkkew,

Sorry for the wait and delay. We have finished the clean-up and released the code now. I will release the pre-trained models in a day or two :)

Kind regards,
Haoyu
