### ISSUE TITLE
PyInit_MultiScaleDeformableAttention

### ISSUE THREAD

**Issue by PL2584718785** [ziplab/FASeg#2]
您好，大佬 请问下这个问题应该如何解决呢，谢谢
**ImportError: dynamic module does not define module export function (PyInit_MultiScaleDeformableAttention)**

**Comment by Charleshhy** [comment]
Hi~

Thanks for your interest in our work!

Try the following commands under the home directory of this project (make sure you have gcc installed):

```
cd mask2former/modeling/pixel_decoder/ops
sh make.sh
```

Also, I am planning to update this project in December (fix some bugs and add more results)! Please stay tuned!

Kind regards,
Haoyu

**Comment by GitHubYuxiao** [comment]
> 您好，大佬 请问下这个问题应该如何解决呢，谢谢 **ImportError: dynamic module does not define module export function (PyInit_MultiScaleDeformableAttention)**

hi，have you save this problem，I also meet it
