### ISSUE TITLE
positional queries generation problem

### ISSUE THREAD

**Issue by CQ-AI** [ziplab/FASeg#3]
Good Job!!! You claim the positional queries are dynamically generated conditioned on the cross-attention scores in the paper. However, in the code, the positional queries are generated conditioned on the activation map of the predicted masks. Could you explain why it is not consistent?

**Comment by Charleshhy** [comment]
Hi CQ-AI,

Thanks for your interest in our work! The core code block of our DFPQ is from [L586](https://github.com/ziplab/FASeg/blob/main/mask2former/modeling/transformer_decoder/mask2former_transformer_decoder.py#L586)-589, which is conditioned on the cross-attention scores. However, as we don't have cross-attention scores in the first transformer decoder layer, we use the normalized predicted mask to generate DFPQ in [L508](https://github.com/ziplab/FASeg/blob/main/mask2former/modeling/transformer_decoder/mask2former_transformer_decoder.py#L508)-L509.

Kind regards,
Haoyu
