### ISSUE TITLE
PyInit_MultiScaleDeformableAttention

### ISSUE THREAD

**Issue by GitHubYuxiao** [ziplab/FASeg#4]
As you operation step by step,I encounter ImportError: dynamic module does not define module export function,is it a bug?

**Comment by Charleshhy** [comment]
Hi GitHubYuxiao,

Thanks for your interest in our project! I cannot reproduce your error but this looks like an issue with `pip` in python2. Check out the fix [here](https://github.com/pybind/python_example/issues/99) and let me know how it goes.

Kind regards,
Haoyu

**Comment by Charleshhy** [comment]
Close this issue due to no further activity.
